/**
 * Source : https://leetcode.com/problems/find-the-difference/
 * Author : Zhuang Ma
 * Email  : chumpma(at)gmail.com
 * Date   : 2016-11-02
 * */

/**
 * Problem:
 * Given two strings s and t which consist of only lowercase letters.
 * 
 * String t is generated by random shuffling string s and then add one more letter at a random position.
 * 
 * Find the letter that was added in t.
 * 
 * Example:
 * 
 * Input:
 * s = "abcd"
 * t = "abcde"
 * 
 * Output:
 * e
 * 
 * Explanation:
 * 'e' is the letter that was added.
 */

class Solution {
public:
    char findTheDifference(string s, string t) {
        char ch = s[0];
        for (int i = 1; i < s.size(); i++) {
            ch ^= s[i];
        }

        for (int i = 0; i < t.size(); i++) {
            ch ^= t[i];
        }

        return ch;
    }
};
